config/routes.rb
ProjectSabertooth::Application.routes.draw do

   root 'home#index'

  match "login/login" => "login#login", :as=>"user_login", :via=>[:post]
  match "login/logout" => 'login#logout', :as=>'user_logout', :via=>[:get]
  match "document/:id/edit" => "document#edit", :as=>"ajax_edit_doc", :via=>[:post]
  match "document/:id/options" => "document#options", :as=>"doc_options", :via=>[:get]
  match "document/:id/options_save" => "document#options_save", :as=>"doc_options_save", :via=>[:post]
  resources :login
  resources :home
  resources :about
  resources :document

  

end

app/views/shared/_content.html.haml
.col-md-6.col-md-offset-3
    .container-body.jumbotron
        .jumbotron
            %h1=title
            .text-body
                = yield(:text)
        = yield(:rest)

app/views/shared/_large_format.html.haml
.col-md-10.col-md-offset-1
    .panel
        .panel-body
            .row.rowfix
                .col-md-3.col-extend{:style=>"border-right: 1px solid #777"}
                    = yield(:left)
                .col-md-9.col-extend
                    = yield(:right)

app/views/shared/_navbar.html.haml
.container.navbar-fixed-top
    %nav.navbar.navbar-default.scheme-primary-dark{:role=>"navigation"}
        %a.navbar-brand Project Sabertooth
        .collapse.navbar-collapse.navbar-ex1-collapse.navbar-right
            %ul.nav.navbar-nav
                %li{:class=>('active' if @active_tab == 'Home')}
                    %a{:href=>home_index_path} Home
                %li{:class=>('active' if @active_tab == 'AboutSaberTooth')}
                    %a{:href=>about_index_path} About
                - if loggedIn?
                    %li{:class=>('active' if @active_tab == "DocumentIndex")}
                        %a{:href=>document_index_path} My Documents
                    %li
                        .navbar-text
                            Welcome #{@user[:display_name]} (<a class="navbar-link" href=#{user_logout_url}>logout</a>)
                - else
                    %li{:class=>('active' if @active_tab == 'LogIn')}
                        %a{:href=>login_index_path} Login

app/views/shared/_need_login.html.haml
- content_for(:text) do
    Permission denied. Perhaps you need to log in?
= render :partial => "shared/content", :locals => {:title => "Please Log In" }