config/routes.rb
ProjectSabertooth::Application.routes.draw do

   root 'home#index'

  match "login/login" => "login#login", :as=>"user_login", :via=>[:post]
  match "login/logout" => 'login#logout', :as=>'user_logout', :via=>[:get]
  match "document/:id/edit" => "document#edit", :as=>"ajax_edit_doc", :via=>[:post]
  match "document/:id/options" => "document#options", :as=>"doc_options", :via=>[:get]
  match "document/:id/options_save" => "document#options_save", :as=>"doc_options_save", :via=>[:post]
  resources :login
  resources :home
  resources :about
  resources :document

  

end

app/controllers/login_controller.rb
class LoginController < ApplicationController
	include LoginHelper
	#The default login page
	def index
	end

    def login
        login_params = params.require(:user).permit!

        email, password = login_params[:email_address], login_params[:password]
        
        user = get_user(email, password)
        if user != nil
            @status = "Valid"
            token = new_nonce(32)
            session[:email_address] = user[:email_address]
            session[:session_token] = Base64.encode64(token)
            user[:session_token] = hash_password(token, "")
			user.save()
            @user = user
        else 
            @status = "Notvalid"
            flash[:error] = "Invalid Email and/or Password"
            redirect_to login_index_path
        end
    end

    def logout
        if session.has_key?(:email_address)
            session.delete(:email_address)
            session.delete(:session_token)
        end
		redirect_to root_url
    end

	def create
        #Permit access to the entire :user hash
        user = params.require(:user).permit!
        
        if user[:email_address] == ""
            flash[:error] = "Email address required."
            redirect_to new_login_path
        elsif user[:display_name] == ""
            flash[:error] = "Display name required."
            redirect_to new_login_path
        elsif user[:password] != user[:password_confirmation]
            flash[:error] = "Passwords do not match."
            redirect_to new_login_path
        elsif user[:password].length < 4
            flash[:error] = "Password should be atleast 4 characters long."
            redirect_to new_login_path
        end

        user[:password_salt] = new_salt()
        user[:password_hash] = hash_password(user[:password], user[:password_salt])

        #Get rid of plaintext passwords
        user.delete(:password)
        user.delete(:password_confirmation)

        newUser = User.new(user)
        

        if newUser.save()
            @create_successful = "success"
            token = new_nonce(32)
            session[:email_address] =newUser[:email_address]
            session[:session_token] = Base64.encode64(token)
            newUser[:session_token] = hash_password(token, "")
            newUser.save()
            Document.new(:owner_id=>newUser[:id], :name=>"Demo Ruby Code", :content=>"# Variables and expressions.\na = 10\nb = 3 * a + 2\nprintf(\"%d %d\n\", a, b);\n\n# Type is dynamic.\nb = \"A string\"\nc = 'Another String'\nprint b + \" and \" + c + \" + \"\\n\"").save()
            Document.new(:owner_id=>newUser[:id], :name=>"Demo JS Code", :content=>"var firstname;\nfirstname=\"Hege\";\ndocument.write(firstname);\ndocument.write(\"<br>\");\nfirstname=\"Tove\";\ndocument.write(firstname);").save()
            @user = newUser
        end
	end
end

app/helpers/login_helper.rb
module LoginHelper
	def get_session(email_address, session_token)
		if email_address == nil or session_token == nil
			return nil
		end
		login_user = User.where(:email_address=>email_address).first
        if login_user != nil
            if login_user[:email_address] == email_address and login_user[:session_token] == hash_password(Base64.decode64(session_token), "")
                return login_user[:id]
            end
        end
        return nil
	end

    def new_salt()
        salt = ""
        salt << new_nonce(8)
        return Base64.encode64(salt)
    end

    def new_nonce(len)
        nonce = ""
        for i in 0..len
            nonce << rand(256)
        end
        return nonce
    end

    #Takes a plaintext password and a Base64 encoded salt and computes the hash
    def hash_password(password, salt)
        pwHash = Digest::SHA2.new(256) 
        pwHash << password << Base64.decode64(salt)
        return pwHash.to_s
    end

    def get_user(email_address, password)
        possible_user = User.where(:email_address=>email_address).first
        if possible_user == nil
            return nil
        end
        paramPass = hash_password(password, possible_user[:password_salt])
        if paramPass == possible_user[:password_hash]
            return possible_user
        end
        return nil
    end
end

app/views/login/create.html.haml
- @active_tab = "LogIn"
- content_for(:rest) do
    %a.btn.btn-primary.btn{:role=>"button",:href=>home_index_path} Go To Your Home

- content_for(:text) do
    - if @create_successful
        %p Your account has been created!
    - else
        %p Failed to create account!

= render :partial => "shared/content", :locals => { :title => @title }

app/views/login/index.html.haml
- @active_tab = "LogIn"
- content_for(:rest)

- content_for(:text) do
    - if flash[:error] != nil
        .alert.alert-danger
            =flash[:error]
    Login to access your account!
    %br
    New?
    %a{:href=>new_login_path} Create an account!
    = form_tag user_login_path do
        %br
        .form-group
            %input.form-control{:type=>"text", :placeholder=>"Email", :name=>"user[email_address]"}
        .form-group
            %input.form-control{:type=>"password", :placeholder=>"Password", :name=>"user[password]"}
        %button.btn.btn-default{:type=>"submit"} Login

= render :partial => "shared/content", :locals => { :title => "Login" }

app/views/login/login.html.haml
- @active_tab = "LogIn"
- content_for(:rest) do
    %a.btn.btn-primary.btn{:role=>"button",:href=>home_index_path} Go To Your Home

- content_for(:text) do
    You've logged in successfully!

= render :partial => "shared/content", :locals => { :title => "Logged In!" }

app/views/login/new.html.haml
- content_for(:text) do
    = form_tag login_index_path do
        .panel
            .col-md-6
                - if flash[:error] != nil
                    .alert.alert-danger
                        =flash[:error]
                %br
                .form-group
                    %input.form-control{:type=>"text", :placeholder=>"Display Name", :name=>"user[display_name]"}
                .form-group
                    %input.form-control{:type=>"text", :placeholder=>"Email Address", :name=>"user[email_address]"}
                .form-group
                    %input.form-control{:type=>"password", :placeholder=>"Password", :name=>"user[password]"}
                .form-group
                    %input.form-control{:type=>"password", :placeholder=>"Confirm Password", :name=>"user[password_confirmation]"}

                .btn-group#pricing
                    %button.btn.btn-default{:type=>"button"} Free
                    %button.btn.btn-default{:type=>"button"} Hobbyist
                    %button.btn.btn-default{:type=>"button"} Professional
                    %button.btn.btn-default{:type=>"button"} Enterprise

                .input-group
                    %span.input-group-addon
                        %input{:type=>"checkbox"}
                    %span.input-group-addon I accept Project Sabertooth's Terms and Conditions.

            .col-md-6
                %table.table.table-striped.table-bordered
                    %tr
                        %th{:width=>"25%"} Account type
                        %th{:width=>"75%"} Benefits
                        %th{:width=>"25%"} Cost (Monthly)
                    %tr
                        %td Free
                        %td
                            Put details here!
                        %td $0.00
                    %tr
                        %td Hobbyist
                        %td
                            Put details here!
                        %td $2.99
                    %tr
                        %td Professional
                        %td
                            Put details here!
                        %td $9.99
                    %tr
                        %td Enterprise
                        %td
                            Put details here!
                        %td $19.99

        .col-md-offset-2
            %button.btn.btn-default{:type=>"submit"} Create Account


= render :partial => "shared/content", :locals => { :title => "Create A New Account" }

app/views/login/show.html.haml
.col-md-6.col-md-offset-3
  .panel.panel-primary
    .panel-heading.panel-title
      %h4 Login
    .panel-body
      Login to access your account!
      .form-signin
        %br
        .input-group
          %input.form-control{:type=>"text", :placeholder=>"Username"}