config/routes.rb
ProjectSabertooth::Application.routes.draw do

   root 'home#index'

  match "login/login" => "login#login", :as=>"user_login", :via=>[:post]
  match "login/logout" => 'login#logout', :as=>'user_logout', :via=>[:get]
  match "document/:id/edit" => "document#edit", :as=>"ajax_edit_doc", :via=>[:post]
  match "document/:id/options" => "document#options", :as=>"doc_options", :via=>[:get]
  match "document/:id/options_save" => "document#options_save", :as=>"doc_options_save", :via=>[:post]
  resources :login
  resources :home
  resources :about
  resources :document

  

end

app/models/document.rb
class Document < ActiveRecord::Base
end

app/controllers/document_controller.rb
class DocumentController < ApplicationController
	def index
		if loggedIn?
			@documents = Document.where(:owner_id=>@user[:id])
			if session[:current_doc] != nil
				@current_doc = Document.find(session[:current_doc])
			end
		end
	end

	def show
		session[:current_doc] = params[:id]
		redirect_to document_index_path
	end

    def options_save
        params.permit(:id)
        params.permit(:perms)
        params.require(:perms).permit(:user_id,:read,:write,:share)

        perms = params[:perms] 
        users = User.where( :email_address => perms[:user_id] )
        
        if users.length != 1
            @failed = true
        else
            dperm = DocumentPermissions.new
            dperm.created_at = 0
            dperm.updated_at = 0
            dperm.document_id = params[:id]
            dperm.user_id = users[0].id
            dperm.perms = (perms[:read] << 2) + (perms[:write] << 1) + perms[:share]

            puts("Inserting: " + dperm.attributes.to_s)
            @failed = !(dperm.save())
        end
    end

    def options
        params.permit(:id) 
        if params[:id] != nil
            id = params[:id] ;
            doc_perms_list = DocumentPermissions.where( :document_id => id )
            @hashes = [] ;

            doc_perms_list.each do |perm|
                user = Users.find(perm.user_id)
                hash = { :user=>user.name, :perms=>perm.perms }
                hashes << hash
            end
        end
    end

	def edit
		if loggedIn?
			params.permit(:id, :contents, :title)
            if params[:id] != nil and params[:contents] != nil and params[:title] != nil
                doc = Document.find(params[:id])
                doc[:content] = params[:contents]
                doc[:name] = params[:title]
                doc.save()
                render :json => {:status=>"Success" + params[:id].to_s + params[:contents].to_s}
            else
                render :json => {:status=>"Failed" + params[:id].to_s + params[:contents].to_s}
            end
		end
	end

    def new
        if loggedIn?
            new_doc = Document.new(:owner_id=>@user[:id], :name=>"Untitled Document", :content=>"")
            new_doc.save
            session[:current_doc] = new_doc[:id]
            redirect_to document_index_path
        end
    end
    def destroy
        if loggedIn?
            params.permit(:id)
            doc = Document.find(params[:id])
            if doc != nil
                session.delete(:current_doc)
                doc.destroy
            end
            redirect_to document_index_path
        end
    end
end

app/helpers/document_helper.rb
module DocumentHelper
end

app/views/document/index.html.haml
- @active_tab = "DocumentIndex"
- @onload = "docLoad()"

- if loggedIn?
    - content_for(:left) do
        .btn-group.btn-group-justified.bottom
            %a.btn.btn-default{:href=>new_document_path} New Doc
            - if @current_doc != nil
                = link_to 'Destroy', document_path(@current_doc), :confirm => 'Are you sure?', :method => :delete, :class=>"btn btn-default"
        %br
        %ul.nav.nav-pills.nav-stacked
            - @documents.each do |doc|
                - if @current_doc != nil and @current_doc[:id] == doc[:id]
                    %li.active
                        %a#menu_entry{:href=>document_path(doc)}
                            = doc.name
                -else
                    %li
                        %a{:href=>document_path(doc)}
                            = doc.name

    - content_for(:right) do
        -if @current_doc != nil
            %div#document_id{:style=>"display: none;"}
                =@current_doc[:id]
            .input-group
                %input.form-control#document_title{:type=>"text", :value=>@current_doc[:name]}
                %span.input-group-addon#doc_badge
                    Saved
                %a.btn-primary.input-group-addon.btn{:href=>doc_options_path(@current_doc[:id])} Options
            %select.form-control{:onchange=>"setHighlighting(this)"}
                %option Syntax Highlighting...
                %option{:value=>"plaintext"} Plaintext
                %option{:value=>"text/x-ruby"} Ruby
                %option{:value=>"javascript"} Javascript
            %br
            %textarea.form-control#main_document{:rows=>20}
                = preserve do
                    =@current_doc[:content]
            
    = render :partial => "shared/large_format"
- else
    = render :partial => "shared/need_login"

app/views/document/options.html.haml
- content_for(:text) do
    %h3 Permissions
    - @hashes.each do | elem |
        %a User #{elem[:user]}
        %a Perms #{elem[:perms]}
    %h3 New
    = form_tag doc_options_save_path do
        .input-group
        %span
            %input{:type=>"text",:placeholder=>"User",:name=>"perms[user_id]"}
            %input{:type=>"checkbox",:name=>"perms[read]"}
                Read
            %input{:type=>"checkbox",:name=>"perms[write]"}
                Write
            %input{:type=>"checkbox",:name=>"perms[share]"}
                Share
        %button.btn.btn-default{:type=>"submit"} Save

= render :partial => "shared/content", :locals => { :title => "Options" }

app/views/document/options_save.html.haml
- content_for(:text) do
    - if not @failed
        %h3 Options Saved!
    - else
        %h3 Options failed to save!

= render :partial => "shared/content", :locals => { :title => "" }